### ISSUE TITLE
Chrome culls .kepub sub-extension when saving

### ISSUE THREAD

**Issue by joshuagarnerxyz** [standardebooks/guy-de-maupassant_short-fiction_ernest-boyd_storm-jameson_jeffery-e-jeffery_lafcadio-hearn_m-walter-#1]
When attempting to save the kepub version of the file on Google Chrome (107.0.5304.89), the part of the filename consisting of "elow-brown-co-inc_francis-steegmuller.kepub" is culled, presumably because of the length of the filename. As a result, the kepub file will not function properly unless renamed.

**Comment by acabal** [comment]
Seems to work fine in both Firefox and Chromium on Linux. This is probably a Chrome bug, which you can report to them, unless it's a limitation of your platform. Though the filename is still below the max length imposed by Windows AFAIK.
